development:
  adapter: postgresql
  encoding: unicode
  database: movie_dev
  pool: 5
  username: carlos
  password: latino

test:
  adapter: postgresql
  encoding: unicode
  database: movie_test
  pool: 5
  username: carlos
  password: latino

production:
  adapter: postgresql
  encoding: unicode
  database: movie_prod
  pool: 5
  username: carlos
  password: latino